error id: 28unHxfSW5G/w1yeZooIQQ==
### Bloop error:

at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
#### Short summary: 

at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)