error id: +XG9ztdMurJpQ+RhRCEMBw==
### Bloop error:

at scala.util.Success.$anonfun$map$1(Try.scala:255)
#### Short summary: 

at scala.util.Success.$anonfun$map$1(Try.scala:255)